# Taken from: 
# https://github.com/fly-apps/nginx/blob/master/fly.toml

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 2000
    soft_limit = 200

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.http_checks]]
    interval = 10000
    method = "get"
    path = "/healthz"
    protocol = "http"
    timeout = 2000
    [services.http_checks.headers]
      Host = "health.check"